In [1]:
import pandas as pd
from IPython.display import display

# Set ALL display options
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("data/master_dataset_v4.csv")

# This will show the full dataframe with scroll
print("\n" + "="*80)
print("FIRST 10 ROWS")
print("="*80)
display(df.head(10))  # Uses display() instead of print()

print("\n" + "="*80)
print("SHAPE")
print("="*80)
display(df.shape)

================================================================================
FIRST 10 ROWS
================================================================================

,organization,title,location,date_posted,deadline,source_url,country,work_arrangement,title_language,job_category,seniority_level
0,Amref,Monitoring & Evaluation Associate - Global Fund TB Project,Nairobi,2026-07-14 12:36:37.738000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137657149,Kenya,Onsite,English,M&E,Mid/Standard
1,Amref,Program Manager-SRHR,Kampala,2026-07-14 07:50:55.688000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137606414,Uganda,Onsite,English,Program/Project Management,Mid/Standard
2,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:50:22.263000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136172959,Kenya,Onsite,English,Health,Senior
3,Amref,Senior Lecturer - Clinical psychology,Nairobi,2026-07-07 08:48:46.626000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136171985,Kenya,Onsite,English,Health,Senior
4,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:33:51.023000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136169179,Kenya,Onsite,English,Health,Senior
5,Amref,Innovative Training Specialist,Nairobi,2026-06-22 09:43:45.966000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000133311585,Kenya,Onsite,English,Other/Uncategorized,Mid/Standard
6,Amref,Readvertisement - TVET Trainer Counselling Psychology,Nairobi,2025-11-14 09:10:58.598000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000093646848,Kenya,Onsite,English,Health,Mid/Standard
7,GiveDirectly,Emergency Community Engagement Associate,GOMA-BENI & BUTEMBO,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714349005,Democratic Republic of Congo,Onsite,English,Other/Uncategorized,Mid/Standard
8,GiveDirectly,"Chief of Staff, Emergency Cash (Senior Manager)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4715777005,Not specified,Remote,English,Other/Uncategorized,Leadership
9,GiveDirectly,"Community Engagement Coordinator, San Joaquin County, CA","San Joaquin County, CA",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4701588005,United States,Onsite,English,Other/Uncategorized,Mid/Standard

================================================================================
SHAPE
================================================================================

(530, 11)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   organization      530 non-null    object
 1   title             530 non-null    object
 2   location          530 non-null    object
 3   date_posted       7 non-null      object
 4   deadline          472 non-null    object
 5   source_url        530 non-null    object
 6   country           530 non-null    object
 7   work_arrangement  530 non-null    object
 8   title_language    530 non-null    object
 9   job_category      530 non-null    object
 10  seniority_level   530 non-null    object
dtypes: object(11)
memory usage: 45.7+ KB

In [3]:
df.head(40)

,organization,title,location,date_posted,deadline,source_url,country,work_arrangement,title_language,job_category,seniority_level
0,Amref,Monitoring & Evaluation Associate - Global Fund TB Project,Nairobi,2026-07-14 12:36:37.738000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137657149,Kenya,Onsite,English,M&E,Mid/Standard
1,Amref,Program Manager-SRHR,Kampala,2026-07-14 07:50:55.688000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137606414,Uganda,Onsite,English,Program/Project Management,Mid/Standard
2,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:50:22.263000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136172959,Kenya,Onsite,English,Health,Senior
3,Amref,Senior Lecturer - Clinical psychology,Nairobi,2026-07-07 08:48:46.626000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136171985,Kenya,Onsite,English,Health,Senior
4,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:33:51.023000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136169179,Kenya,Onsite,English,Health,Senior
5,Amref,Innovative Training Specialist,Nairobi,2026-06-22 09:43:45.966000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000133311585,Kenya,Onsite,English,Other/Uncategorized,Mid/Standard
6,Amref,Readvertisement - TVET Trainer Counselling Psychology,Nairobi,2025-11-14 09:10:58.598000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000093646848,Kenya,Onsite,English,Health,Mid/Standard
7,GiveDirectly,Emergency Community Engagement Associate,GOMA-BENI & BUTEMBO,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714349005,Democratic Republic of Congo,Onsite,English,Other/Uncategorized,Mid/Standard
8,GiveDirectly,"Chief of Staff, Emergency Cash (Senior Manager)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4715777005,Not specified,Remote,English,Other/Uncategorized,Leadership
9,GiveDirectly,"Community Engagement Coordinator, San Joaquin County, CA","San Joaquin County, CA",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4701588005,United States,Onsite,English,Other/Uncategorized,Mid/Standard
10,GiveDirectly,"Country Director, Uganda","Kampala, Uganda",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4614283005,Uganda,Onsite,English,Other/Uncategorized,Leadership
11,GiveDirectly,"Director, Global Talent Acquisition (Remote)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714132005,Not specified,Remote,English,HR,Leadership
12,GiveDirectly,Director of Engineering (Remote),Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4706119005,Not specified,Remote,English,IT/Tech,Leadership
13,GiveDirectly,Field Manager,Field Based,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4710175005,Not specified,Not specified,English,Other/Uncategorized,Mid/Standard
14,GiveDirectly,Gestor De Campo - Auditoria Interna,Mozambique,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4622571005,Mozambique,Onsite,Spanish,Non-English/Unclassified,Non-English/Unclassified
15,GiveDirectly,Head of Strategic Partnerships & Influence (Remote),Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4673881005,Not specified,Remote,English,Other/Uncategorized,Leadership
16,GiveDirectly,"Program Manager, Research","Zomba, Malawi",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4699685005,Malawi,Onsite,English,Research,Mid/Standard
17,GiveDirectly,Remote Sensing Analyst [Contractor],"New York, United States",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4702835005,United States,Onsite,English,Other/Uncategorized,Mid/Standard
18,GiveDirectly,Rwanda Field Officer,Rwanda,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714323005,Rwanda,Onsite,English,Operations/Admin,Mid/Standard
19,GiveDirectly,Rwanda Senior Manager - Field Operations and Programs,Rwanda,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4692032005,Rwanda,Onsite,English,Program/Project Management,Senior
20,GiveDirectly,"Senior Manager, Accounting (Remote - US)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4685803005,Not specified,Remote,English,Finance,Senior
21,GiveDirectly,"Senior Manager, Business Operations (Remote)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4695154005,Not specified,Remote,English,Operations/Admin,Senior
22,GiveDirectly,"Senior Manager, Finance (DRC)","Goma, DRC",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4708207005,Democratic Republic of Congo,Onsite,English,Finance,Senior
23,GiveDirectly,"Senior Manager, Strategic Finance (Remote)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4707837005,Not specified,Remote,English,Finance,Senior
24,GiveDirectly,Senior Software Engineer (Remote),Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4558344005,Not specified,Remote,English,IT/Tech,Senior
25,GiveDirectly,US Program Associate,"Cleveland, OH",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4705093005,United States,Onsite,English,Program/Project Management,Mid/Standard
26,GiveDirectly,"US Program Director, Emergency Cash",Remote - United States,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4694539005,United States,Remote,English,Program/Project Management,Leadership
27,Human Rights Watch,Asia Division Intern,"Tokyo, Japan",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8601979002,Japan,Onsite,English,Other/Uncategorized,Entry/Support
28,Human Rights Watch,"Associate, Asia","London, England, United Kingdom",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8624581002,United Kingdom,Onsite,English,Other/Uncategorized,Mid/Standard
29,Human Rights Watch,Chief Operating Officer,Multiple Locations Considered,NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8408691002,Not specified,Not specified,English,Operations/Admin,Leadership
30,Human Rights Watch,Development & Outreach Department Intern,"Paris, Paris, France",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8601982002,France,Onsite,English,Other/Uncategorized,Entry/Support
31,Human Rights Watch,Development & Outreach Department Intern,"Sydney, New South Wales, Australia",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8601976002,Australia,Onsite,English,Other/Uncategorized,Entry/Support
32,Human Rights Watch,Development & Outreach Department Intern,"Tokyo, Japan",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8601981002,Japan,Onsite,English,Other/Uncategorized,Entry/Support
33,Human Rights Watch,LGBT Rights Program (ECA) Intern,"Berlin, Berlin, Germany",NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8603690002,Germany,Onsite,English,Program/Project Management,Entry/Support
34,Human Rights Watch,"Manager, Enterprise Applications Integration",Multiple Locations Considered,NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8352097002,Not specified,Not specified,English,Other/Uncategorized,Mid/Standard
35,Human Rights Watch,"Researcher, China",Multiple Locations Considered,NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8604670002,Not specified,Not specified,English,Research,Mid/Standard
36,Human Rights Watch,"Researcher, Myanmar",Multiple Locations Considered,NaN,NaN,https://job-boards.greenhouse.io/humanrightswatch/jobs/8536427002,Not specified,Not specified,English,Research,Mid/Standard
37,MSF USA,Anesthesiologists,Medical,NaN,NaN,https://job-boards.greenhouse.io/workoverseas/jobs/4556079008,Not specified,Not specified,English,Health,Mid/Standard
38,MSF USA,Communications Manager,Non-Medical,NaN,NaN,https://job-boards.greenhouse.io/workoverseas/jobs/4552648008,Not specified,Not specified,English,Communications,Mid/Standard
39,MSF USA,Epidemiologists,Medical,NaN,NaN,https://job-boards.greenhouse.io/workoverseas/jobs/4555991008,Not specified,Not specified,English,Health,Mid/Standard

In [4]:
df.isna()

,organization,title,location,date_posted,deadline,source_url,country,work_arrangement,title_language,job_category,seniority_level
0,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,True,True,False,False,False,False,False,False
8,False,False,False,True,True,False,False,False,False,False,False
9,False,False,False,True,True,False,False,False,False,False,False
10,False,False,False,True,True,False,False,False,False,False,False
11,False,False,False,True,True,False,False,False,False,False,False
12,False,False,False,True,True,False,False,False,False,False,False
13,False,False,False,True,True,False,False,False,False,False,False
14,False,False,False,True,True,False,False,False,False,False,False
15,False,False,False,True,True,False,False,False,False,False,False
16,False,False,False,True,True,False,False,False,False,False,False
17,False,False,False,True,True,False,False,False,False,False,False
18,False,False,False,True,True,False,False,False,False,False,False
19,False,False,False,True,True,False,False,False,False,False,False
20,False,False,False,True,True,False,False,False,False,False,False
21,False,False,False,True,True,False,False,False,False,False,False
22,False,False,False,True,True,False,False,False,False,False,False
23,False,False,False,True,True,False,False,False,False,False,False
24,False,False,False,True,True,False,False,False,False,False,False
25,False,False,False,True,True,False,False,False,False,False,False
26,False,False,False,True,True,False,False,False,False,False,False
27,False,False,False,True,True,False,False,False,False,False,False
28,False,False,False,True,True,False,False,False,False,False,False
29,False,False,False,True,True,False,False,False,False,False,False
30,False,False,False,True,True,False,False,False,False,False,False
31,False,False,False,True,True,False,False,False,False,False,False
32,False,False,False,True,True,False,False,False,False,False,False
33,False,False,False,True,True,False,False,False,False,False,False
34,False,False,False,True,True,False,False,False,False,False,False
35,False,False,False,True,True,False,False,False,False,False,False
36,False,False,False,True,True,False,False,False,False,False,False
37,False,False,False,True,True,False,False,False,False,False,False
38,False,False,False,True,True,False,False,False,False,False,False
39,False,False,False,True,True,False,False,False,False,False,False
40,False,False,False,True,True,False,False,False,False,False,False
41,False,False,False,True,True,False,False,False,False,False,False
42,False,False,False,True,True,False,False,False,False,False,False
43,False,False,False,True,True,False,False,False,False,False,False
44,False,False,False,True,True,False,False,False,False,False,False
45,False,False,False,True,True,False,False,False,False,False,False
46,False,False,False,True,True,False,False,False,False,False,False
47,False,False,False,True,True,False,False,False,False,False,False
48,False,False,False,True,True,False,False,False,False,False,False
49,False,False,False,True,True,False,False,False,False,False,False
50,False,False,False,True,True,False,False,False,False,False,False
51,False,False,False,True,True,False,False,False,False,False,False
52,False,False,False,True,True,False,False,False,False,False,False
53,False,False,False,True,True,False,False,False,False,False,False
54,False,False,False,True,True,False,False,False,False,False,False
55,False,False,False,True,True,False,False,False,False,False,False
56,False,False,False,True,True,False,False,False,False,False,False
57,False,False,False,True,True,False,False,False,False,False,False
58,False,False,False,True,False,False,False,False,False,False,False
59,False,False,False,True,False,False,False,False,False,False,False
60,False,False,False,True,False,False,False,False,False,False,False
61,False,False,False,True,False,False,False,False,False,False,False
62,False,False,False,True,False,False,False,False,False,False,False
63,False,False,False,True,False,False,False,False,False,False,False
64,False,False,False,True,False,False,False,False,False,False,False
65,False,False,False,True,False,False,False,False,False,False,False
66,False,False,False,True,False,False,False,False,False,False,False
67,False,False,False,True,False,False,False,False,False,False,False
68,False,False,False,True,False,False,False,False,False,False,False
69,False,False,False,True,False,False,False,False,False,False,False
70,False,False,False,True,False,False,False,False,False,False,False
71,False,False,False,True,False,False,False,False,False,False,False
72,False,False,False,True,False,False,False,False,False,False,False
73,False,False,False,True,False,False,False,False,False,False,False
74,False,False,False,True,False,False,False,False,False,False,False
75,False,False,False,True,False,False,False,False,False,False,False
76,False,False,False,True,False,False,False,False,False,False,False
77,False,False,False,True,False,False,False,False,False,False,False
78,False,False,False,True,False,False,False,False,False,False,False
79,False,False,False,True,False,False,False,False,False,False,False
80,False,False,False,True,False,False,False,False,False,False,False
81,False,False,False,True,False,False,False,False,False,False,False
82,False,False,False,True,False,False,False,False,False,False,False
83,False,False,False,True,False,False,False,False,False,False,False
84,False,False,False,True,False,False,False,False,False,False,False
85,False,False,False,True,False,False,False,False,False,False,False
86,False,False,False,True,False,False,False,False,False,False,False
87,False,False,False,True,False,False,False,False,False,False,False
88,False,False,False,True,False,False,False,False,False,False,False
89,False,False,False,True,False,False,False,False,False,False,False
90,False,False,False,True,False,False,False,False,False,False,False
91,False,False,False,True,False,False,False,False,False,False,False
92,False,False,False,True,False,False,False,False,False,False,False
93,False,False,False,True,False,False,False,False,False,False,False
94,False,False,False,True,False,False,False,False,False,False,False
95,False,False,False,True,False,False,False,False,False,False,False
96,False,False,False,True,False,False,False,False,False,False,False
97,False,False,False,True,False,False,False,False,False,False,False
98,False,False,False,True,False,False,False,False,False,False,False
99,False,False,False,True,False,False,False,False,False,False,False
100,False,False,False,True,False,False,False,False,False,False,False
101,False,False,False,True,False,False,False,False,False,False,False
102,False,False,False,True,False,False,False,False,False,False,False
103,False,False,False,True,False,False,False,False,False,False,False
104,False,False,False,True,False,False,False,False,False,False,False
105,False,False,False,True,False,False,False,False,False,False,False
106,False,False,False,True,False,False,False,False,False,False,False
107,False,False,False,True,False,False,False,False,False,False,False
108,False,False,False,True,False,False,False,False,False,False,False
109,False,False,False,True,False,False,False,False,False,False,False
110,False,False,False,True,False,False,False,False,False,False,False
111,False,False,False,True,False,False,False,False,False,False,False
112,False,False,False,True,False,False,False,False,False,False,False
113,False,False,False,True,False,False,False,False,False,False,False
114,False,False,False,True,False,False,False,False,False,False,False
115,False,False,False,True,False,False,False,False,False,False,False
116,False,False,False,True,False,False,False,False,False,False,False
117,False,False,False,True,False,False,False,False,False,False,False
118,False,False,False,True,False,False,False,False,False,False,False
119,False,False,False,True,False,False,False,False,False,False,False
120,False,False,False,True,False,False,False,False,False,False,False
121,False,False,False,True,False,False,False,False,False,False,False
122,False,False,False,True,False,False,False,False,False,False,False
123,False,False,False,True,False,False,False,False,False,False,False
124,False,False,False,True,False,False,False,False,False,False,False
125,False,False,False,True,False,False,False,False,False,False,False
126,False,False,False,True,False,False,False,False,False,False,False
127,False,False,False,True,False,False,False,False,False,False,False
128,False,False,False,True,False,False,False,False,False,False,False
129,False,False,False,True,False,False,False,False,False,False,False
130,False,False,False,True,False,False,False,False,False,False,False
131,False,False,False,True,False,False,False,False,False,False,False
132,False,False,False,True,False,False,False,False,False,False,False
133,False,False,False,True,False,False,False,False,False,False,False
134,False,False,False,True,False,False,False,False,False,False,False
135,False,False,False,True,False,False,False,False,False,False,False
136,False,False,False,True,False,False,False,False,False,False,False
137,False,False,False,True,False,False,False,False,False,False,False
138,False,False,False,True,False,False,False,False,False,False,False
139,False,False,False,True,False,False,False,False,False,False,False
140,False,False,False,True,False,False,False,False,False,False,False
141,False,False,False,True,False,False,False,False,False,False,False
142,False,False,False,True,False,False,False,False,False,False,False
143,False,False,False,True,False,False,False,False,False,False,False
144,False,False,False,True,False,False,False,False,False,False,False
145,False,False,False,True,False,False,False,False,False,False,False
146,False,False,False,True,False,False,False,False,False,False,False
147,False,False,False,True,False,False,False,False,False,False,False
148,False,False,False,True,False,False,False,False,False,False,False
149,False,False,False,True,False,False,False,False,False,False,False
150,False,False,False,True,False,False,False,False,False,False,False
151,False,False,False,True,False,False,False,False,False,False,False
152,False,False,False,True,False,False,False,False,False,False,False
153,False,False,False,True,False,False,False,False,False,False,False
154,False,False,False,True,False,False,False,False,False,False,False
155,False,False,False,True,False,False,False,False,False,False,False
156,False,False,False,True,False,False,False,False,False,False,False
157,False,False,False,True,False,False,False,False,False,False,False
158,False,False,False,True,False,False,False,False,False,False,False
159,False,False,False,True,False,False,False,False,False,False,False
160,False,False,False,True,False,False,False,False,False,False,False
161,False,False,False,True,False,False,False,False,False,False,False
162,False,False,False,True,False,False,False,False,False,False,False
163,False,False,False,True,False,False,False,False,False,False,False
164,False,False,False,True,False,False,False,False,False,False,False
165,False,False,False,True,False,False,False,False,False,False,False
166,False,False,False,True,False,False,False,False,False,False,False
167,False,False,False,True,False,False,False,False,False,False,False
168,False,False,False,True,False,False,False,False,False,False,False
169,False,False,False,True,False,False,False,False,False,False,False
170,False,False,False,True,False,False,False,False,False,False,False
171,False,False,False,True,False,False,False,False,False,False,False
172,False,False,False,True,False,False,False,False,False,False,False
173,False,False,False,True,False,False,False,False,False,False,False
174,False,False,False,True,False,False,False,False,False,False,False
175,False,False,False,True,False,False,False,False,False,False,False
176,False,False,False,True,False,False,False,False,False,False,False
177,False,False,False,True,False,False,False,False,False,False,False
178,False,False,False,True,False,False,False,False,False,False,False
179,False,False,False,True,False,False,False,False,False,False,False
180,False,False,False,True,False,False,False,False,False,False,False
181,False,False,False,True,False,False,False,False,False,False,False
182,False,False,False,True,False,False,False,False,False,False,False
183,False,False,False,True,False,False,False,False,False,False,False
184,False,False,False,True,False,False,False,False,False,False,False
185,False,False,False,True,False,False,False,False,False,False,False
186,False,False,False,True,False,False,False,False,False,False,False
187,False,False,False,True,False,False,False,False,False,False,False
188,False,False,False,True,False,False,False,False,False,False,False
189,False,False,False,True,False,False,False,False,False,False,False
190,False,False,False,True,False,False,False,False,False,False,False
191,False,False,False,True,False,False,False,False,False,False,False
192,False,False,False,True,False,False,False,False,False,False,False
193,False,False,False,True,False,False,False,False,False,False,False
194,False,False,False,True,False,False,False,False,False,False,False
195,False,False,False,True,False,False,False,False,False,False,False
196,False,False,False,True,False,False,False,False,False,False,False
197,False,False,False,True,False,False,False,False,False,False,False
198,False,False,False,True,False,False,False,False,False,False,False
199,False,False,False,True,False,False,False,False,False,False,False
200,False,False,False,True,False,False,False,False,False,False,False
201,False,False,False,True,False,False,False,False,False,False,False
202,False,False,False,True,False,False,False,False,False,False,False
203,False,False,False,True,False,False,False,False,False,False,False
204,False,False,False,True,False,False,False,False,False,False,False
205,False,False,False,True,False,False,False,False,False,False,False
206,False,False,False,True,False,False,False,False,False,False,False
207,False,False,False,True,False,False,False,False,False,False,False
208,False,False,False,True,False,False,False,False,False,False,False
209,False,False,False,True,False,False,False,False,False,False,False
210,False,False,False,True,False,False,False,False,False,False,False
211,False,False,False,True,False,False,False,False,False,False,False
212,False,False,False,True,False,False,False,False,False,False,False
213,False,False,False,True,False,False,False,False,False,False,False
214,False,False,False,True,False,False,False,False,False,False,False
215,False,False,False,True,False,False,False,False,False,False,False
216,False,False,False,True,False,False,False,False,False,False,False
217,False,False,False,True,False,False,False,False,False,False,False
218,False,False,False,True,False,False,False,False,False,False,False
219,False,False,False,True,False,False,False,False,False,False,False
220,False,False,False,True,False,False,False,False,False,False,False
221,False,False,False,True,False,False,False,False,False,False,False
222,False,False,False,True,False,False,False,False,False,False,False
223,False,False,False,True,False,False,False,False,False,False,False
224,False,False,False,True,False,False,False,False,False,False,False
225,False,False,False,True,False,False,False,False,False,False,False
226,False,False,False,True,False,False,False,False,False,False,False
227,False,False,False,True,False,False,False,False,False,False,False
228,False,False,False,True,False,False,False,False,False,False,False
229,False,False,False,True,False,False,False,False,False,False,False
230,False,False,False,True,False,False,False,False,False,False,False
231,False,False,False,True,False,False,False,False,False,False,False
232,False,False,False,True,False,False,False,False,False,False,False
233,False,False,False,True,False,False,False,False,False,False,False
234,False,False,False,True,False,False,False,False,False,False,False
235,False,False,False,True,False,False,False,False,False,False,False
236,False,False,False,True,False,False,False,False,False,False,False
237,False,False,False,True,False,False,False,False,False,False,False
238,False,False,False,True,False,False,False,False,False,False,False
239,False,False,False,True,False,False,False,False,False,False,False
240,False,False,False,True,False,False,False,False,False,False,False
241,False,False,False,True,False,False,False,False,False,False,False
242,False,False,False,True,False,False,False,False,False,False,False
243,False,False,False,True,False,False,False,False,False,False,False
244,False,False,False,True,False,False,False,False,False,False,False
245,False,False,False,True,False,False,False,False,False,False,False
246,False,False,False,True,False,False,False,False,False,False,False
247,False,False,False,True,False,False,False,False,False,False,False
248,False,False,False,True,False,False,False,False,False,False,False
249,False,False,False,True,False,False,False,False,False,False,False
250,False,False,False,True,False,False,False,False,False,False,False
251,False,False,False,True,False,False,False,False,False,False,False
252,False,False,False,True,False,False,False,False,False,False,False
253,False,False,False,True,False,False,False,False,False,False,False
254,False,False,False,True,False,False,False,False,False,False,False
255,False,False,False,True,False,False,False,False,False,False,False
256,False,False,False,True,False,False,False,False,False,False,False
257,False,False,False,True,False,False,False,False,False,False,False
258,False,False,False,True,False,False,False,False,False,False,False
259,False,False,False,True,False,False,False,False,False,False,False
260,False,False,False,True,False,False,False,False,False,False,False
261,False,False,False,True,False,False,False,False,False,False,False
262,False,False,False,True,False,False,False,False,False,False,False
263,False,False,False,True,False,False,False,False,False,False,False
264,False,False,False,True,False,False,False,False,False,False,False
265,False,False,False,True,False,False,False,False,False,False,False
266,False,False,False,True,False,False,False,False,False,False,False
267,False,False,False,True,False,False,False,False,False,False,False
268,False,False,False,True,False,False,False,False,False,False,False
269,False,False,False,True,False,False,False,False,False,False,False
270,False,False,False,True,False,False,False,False,False,False,False
271,False,False,False,True,False,False,False,False,False,False,False
272,False,False,False,True,False,False,False,False,False,False,False
273,False,False,False,True,False,False,False,False,False,False,False
274,False,False,False,True,False,False,False,False,False,False,False
275,False,False,False,True,False,False,False,False,False,False,False
276,False,False,False,True,False,False,False,False,False,False,False
277,False,False,False,True,False,False,False,False,False,False,False
278,False,False,False,True,False,False,False,False,False,False,False
279,False,False,False,True,False,False,False,False,False,False,False
280,False,False,False,True,False,False,False,False,False,False,False
281,False,False,False,True,False,False,False,False,False,False,False
282,False,False,False,True,False,False,False,False,False,False,False
283,False,False,False,True,False,False,False,False,False,False,False
284,False,False,False,True,False,False,False,False,False,False,False
285,False,False,False,True,False,False,False,False,False,False,False
286,False,False,False,True,False,False,False,False,False,False,False
287,False,False,False,True,False,False,False,False,False,False,False
288,False,False,False,True,False,False,False,False,False,False,False
289,False,False,False,True,False,False,False,False,False,False,False

In [5]:
# Check rows where both date_posted and deadline columns have missing values
missing_both = df[df["date_posted"].isna() & df["deadline"].isna()]
missing_both["organization"].value_counts()

organization
MSF USA               21
GiveDirectly          20
Human Rights Watch    10
Name: count, dtype: int64

In [6]:
# Check for missing date_posted values in DevNet Jobs
devnetjobs_rows = df[df["organization"] != "Amref"]
devnetjobs_rows = devnetjobs_rows[~devnetjobs_rows["organization"].isin(["MSF USA", "GiveDirectly", "Human Rights Watch"])]

print(f"Total non-ATS (DevNetJobs) rows: {len(devnetjobs_rows)}")
print(f"Missing date_posted in DevNetJobs: {devnetjobs_rows['date_posted'].isna().sum()}")
print(f"Missing deadline in DevNetJobs: {devnetjobs_rows['deadline'].isna().sum()}")

Total non-ATS (DevNetJobs) rows: 471
Missing date_posted in DevNetJobs: 471
Missing deadline in DevNetJobs: 0

In [7]:
# Check where specific data source the 6 duplicate organisations fixed by fuzzy matching are from
duplicate_org_names = [
    "Care", "CARE", "Goal", "GOAL", "Searca", "SEARCA",
    "The Better Cotton Initiative", "Better Cotton Initiative",
    "Asian Development Bank (ADB)", "Asian Development Bank",
    "United Nations University (UNU)", "United Nations University"
]

check_source = df[df["organization"].isin(duplicate_org_names)]
check_source[["organization", "source_url"]].drop_duplicates()

,organization,source_url
65,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=311115
66,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=311116
79,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=311114
94,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=311117
99,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=311118
149,SEARCA,https://devnetjobs.org/jobdescription.aspx?job_id=310280
218,United Nations University,https://devnetjobs.org/jobdescription.aspx?job_id=310889
233,GOAL,https://devnetjobs.org/jobdescription.aspx?job_id=310761
284,SEARCA,https://devnetjobs.org/jobdescription.aspx?job_id=310702
292,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=310594
298,Asian Development Bank,https://devnetjobs.org/jobdescription.aspx?job_id=310595
314,GOAL,https://devnetjobs.org/jobdescription.aspx?job_id=310631
320,CARE,https://devnetjobs.org/jobdescription.aspx?job_id=308949
377,SEARCA,https://devnetjobs.org/jobdescription.aspx?job_id=310277
389,Better Cotton Initiative,https://devnetjobs.org/jobdescription.aspx?job_id=310451
391,Better Cotton Initiative,https://devnetjobs.org/jobdescription.aspx?job_id=310452
412,United Nations University,https://devnetjobs.org/jobdescription.aspx?job_id=310406
413,United Nations University,https://devnetjobs.org/jobdescription.aspx?job_id=310407
476,CARE,https://devnetjobs.org/jobdescription.aspx?job_id=308951
486,Better Cotton Initiative,https://devnetjobs.org/jobdescription.aspx?job_id=308881

In [8]:
# Check actual column names
df.columns

Index(['organization', 'title', 'location', 'date_posted', 'deadline',
       'source_url', 'country', 'work_arrangement', 'title_language',
       'job_category', 'seniority_level'],
      dtype='object')

In [9]:
df.head(20)

,organization,title,location,date_posted,deadline,source_url,country,work_arrangement,title_language,job_category,seniority_level
0,Amref,Monitoring & Evaluation Associate - Global Fund TB Project,Nairobi,2026-07-14 12:36:37.738000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137657149,Kenya,Onsite,English,M&E,Mid/Standard
1,Amref,Program Manager-SRHR,Kampala,2026-07-14 07:50:55.688000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137606414,Uganda,Onsite,English,Program/Project Management,Mid/Standard
2,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:50:22.263000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136172959,Kenya,Onsite,English,Health,Senior
3,Amref,Senior Lecturer - Clinical psychology,Nairobi,2026-07-07 08:48:46.626000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136171985,Kenya,Onsite,English,Health,Senior
4,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07 08:33:51.023000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136169179,Kenya,Onsite,English,Health,Senior
5,Amref,Innovative Training Specialist,Nairobi,2026-06-22 09:43:45.966000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000133311585,Kenya,Onsite,English,Other/Uncategorized,Mid/Standard
6,Amref,Readvertisement - TVET Trainer Counselling Psychology,Nairobi,2025-11-14 09:10:58.598000+00:00,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000093646848,Kenya,Onsite,English,Health,Mid/Standard
7,GiveDirectly,Emergency Community Engagement Associate,GOMA-BENI & BUTEMBO,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714349005,Democratic Republic of Congo,Onsite,English,Other/Uncategorized,Mid/Standard
8,GiveDirectly,"Chief of Staff, Emergency Cash (Senior Manager)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4715777005,Not specified,Remote,English,Other/Uncategorized,Leadership
9,GiveDirectly,"Community Engagement Coordinator, San Joaquin County, CA","San Joaquin County, CA",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4701588005,United States,Onsite,English,Other/Uncategorized,Mid/Standard
10,GiveDirectly,"Country Director, Uganda","Kampala, Uganda",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4614283005,Uganda,Onsite,English,Other/Uncategorized,Leadership
11,GiveDirectly,"Director, Global Talent Acquisition (Remote)",Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714132005,Not specified,Remote,English,HR,Leadership
12,GiveDirectly,Director of Engineering (Remote),Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4706119005,Not specified,Remote,English,IT/Tech,Leadership
13,GiveDirectly,Field Manager,Field Based,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4710175005,Not specified,Not specified,English,Other/Uncategorized,Mid/Standard
14,GiveDirectly,Gestor De Campo - Auditoria Interna,Mozambique,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4622571005,Mozambique,Onsite,Spanish,Non-English/Unclassified,Non-English/Unclassified
15,GiveDirectly,Head of Strategic Partnerships & Influence (Remote),Remote,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4673881005,Not specified,Remote,English,Other/Uncategorized,Leadership
16,GiveDirectly,"Program Manager, Research","Zomba, Malawi",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4699685005,Malawi,Onsite,English,Research,Mid/Standard
17,GiveDirectly,Remote Sensing Analyst [Contractor],"New York, United States",NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4702835005,United States,Onsite,English,Other/Uncategorized,Mid/Standard
18,GiveDirectly,Rwanda Field Officer,Rwanda,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4714323005,Rwanda,Onsite,English,Operations/Admin,Mid/Standard
19,GiveDirectly,Rwanda Senior Manager - Field Operations and Programs,Rwanda,NaN,NaN,https://job-boards.greenhouse.io/givedirectly/jobs/4692032005,Rwanda,Onsite,English,Program/Project Management,Senior

In [10]:
# Check if hybrid and roving work_arrangements exist in the data set
# Hybrid only exists in the location column at the moment
hybrid_check = df[df["location"].str.contains("hybrid", case=False, na=False)]
roving_check = df[df["location"].str.contains("roving", case=False, na=False)]

print(f"Rows mentioning 'Hybrid': {len(hybrid_check)}")
print(f"Rows mentioning 'Roving': {len(roving_check)}")

print("\n=== Hybrid matches ===")
print(hybrid_check[["organization", "location"]].to_string())

print("\n=== Roving matches ===")
print(roving_check[["organization", "location"]].to_string())

Rows mentioning 'Hybrid': 8
Rows mentioning 'Roving': 0

=== Hybrid matches ===
                                organization                                                      location
353                                   Verian                       Location: Remote/Hybrid, United Kingdom
389                 Better Cotton Initiative                     Location: London (Hybrid), United Kingdom
398  Cambridge University Press & Assessment  Location: Makati City, Metro Manila (Hybrid), United Kingdom
415           The Chan Zuckerberg Initiative                   Location: Redwood City, CA (Hybrid), Canada
416                  ClimateWorks Foundation                       Location: Global Hybrid, United Kingdom
421           The Chan Zuckerberg Initiative                   Location: Redwood City, CA (Hybrid), Canada
439                         Lumos Foundation                     Location: London / Hybrid, United Kingdom
461       The Center for Reproductive Rights                Location: New York City ,Hybrid, United States

=== Roving matches ===
Empty DataFrame
Columns: [organization, location]
Index: []

In [11]:
# Check current country/work_arrangement for the 8 Hybrid rows
hybrid_check = df[df["location"].str.contains("hybrid", case=False, na=False)]
print(hybrid_check[["organization", "location", "country", "work_arrangement"]].to_string())

                                organization                                                      location         country work_arrangement
353                                   Verian                       Location: Remote/Hybrid, United Kingdom  United Kingdom           Remote
389                 Better Cotton Initiative                     Location: London (Hybrid), United Kingdom  United Kingdom           Onsite
398  Cambridge University Press & Assessment  Location: Makati City, Metro Manila (Hybrid), United Kingdom  United Kingdom           Onsite
415           The Chan Zuckerberg Initiative                   Location: Redwood City, CA (Hybrid), Canada          Canada           Onsite
416                  ClimateWorks Foundation                       Location: Global Hybrid, United Kingdom  United Kingdom  Regional/Global
421           The Chan Zuckerberg Initiative                   Location: Redwood City, CA (Hybrid), Canada          Canada           Onsite
439                         Lumos Foundation                     Location: London / Hybrid, United Kingdom  United Kingdom           Onsite
461       The Center for Reproductive Rights                Location: New York City ,Hybrid, United States   United States           Onsite

In [12]:
# Explore the work_arrangement column
df["work_arrangement"].value_counts()

work_arrangement
Onsite             445
Not specified       40
Remote              27
Regional/Global     18
Name: count, dtype: int64

In [13]:
# Further explore the location column by checking the "not specified" category
not_specified = df[df["work_arrangement"] == "Not specified"]
print(f"Total 'Not specified' rows: {len(not_specified)}")
print(not_specified[["organization", "location"]].to_string())

Total 'Not specified' rows: 40
                                                  organization                       location
13                                                GiveDirectly                    Field Based
29                                          Human Rights Watch  Multiple Locations Considered
34                                          Human Rights Watch  Multiple Locations Considered
35                                          Human Rights Watch  Multiple Locations Considered
36                                          Human Rights Watch  Multiple Locations Considered
37                                                     MSF USA                        Medical
38                                                     MSF USA                    Non-Medical
39                                                     MSF USA                        Medical
40                                                     MSF USA                    Non-Medical
41                                                     MSF USA                    Non-Medical
42                                                     MSF USA                    Non-Medical
43                                                     MSF USA                        Medical
44                                                     MSF USA                        Medical
45                                                     MSF USA                    Non-Medical
46                                                     MSF USA                        Medical
47                                                     MSF USA                        Medical
48                                                     MSF USA                        Medical
49                                                     MSF USA                        Medical
50                                                     MSF USA                        Medical
51                                                     MSF USA                    Non-Medical
52                                                     MSF USA                        Medical
53                                                     MSF USA                        Medical
54                                                     MSF USA                    Non-Medical
55                                                     MSF USA                        Medical
56                                                     MSF USA                    Non-Medical
57                                                     MSF USA                    Non-Medical
60                             Reporters Sans Frontières (RSF)    Location: Regional / Global
84          International Planned Parenthood Federation (IPPF)    Location: Regional / Global
132                                                       IPPF    Location: Regional / Global
140                                                     Medair    Location: Regional / Global
170                    African Tax Administration Forum (ATAF)    Location: Regional / Global
181                                                       Qcin    Location: Regional / Global
221                                                Mati Carbon    Location: Regional / Global
231                                             Global Citizen    Location: Regional / Global
260                                      Winrock International    Location: Regional / Global
463  CIMMYT - International Maize and Wheat Improvement Center    Location: Regional / Global
466                                             Deutsche Welle    Location: Regional / Global
494                                              One Acre Fund    Location: Regional / Global
498                     Urgent Action Fund-Africa (UAF-Africa)    Location: Regional / Global
519                                          Cultural Survival    Location: Regional / Global

In [14]:
# Manually check roles geographical distribution
scope_keywords_check = df["location"].str.contains(
    "multi|pan-|multiple location|zone|cluster", case=False, na=False
)
print(df[scope_keywords_check]["location"].value_counts())

location
Multiple Locations Considered                4
Location: Multiple Locations Across, Iraq    1
Name: count, dtype: int64

In [15]:
# Check the geographical distribution of roles per country
df["country"].value_counts()

country
United States                   84
Not specified                   61
United Kingdom                  42
Switzerland                     37
Kenya                           26
Belgium                         17
Democratic Republic of Congo    11
Philippines                     10
Italy                           10
Canada                           9
France                           8
Rwanda                           8
Ethiopia                         7
Tanzania                         7
Palestinian Territory            7
Mexico                           6
Brazil                           6
Ukraine                          6
Uganda                           6
Nigeria                          5
Sweden                           5
Senegal                          5
Malawi                           5
Sudan                            5
South Korea                      5
Madagascar                       4
Japan                            4
Bangladesh                       4
Turkey                           4
Germany                          4
Qatar                            4
Indonesia                        4
Fiji                             4
South Sudan                      4
Syrian Arab Republic             3
Pakistan                         3
Chad                             3
Netherlands                      3
Lebanon                          3
Guinea                           3
Jordan                           3
Colombia                         3
South Africa                     3
Singapore                        3
Austria                          2
Vietnam                          2
Venezuela                        2
Sierra Leone                     2
New Caledonia                    2
Albania                          2
Cambodia                         2
Benin                            2
Zambia                           2
Denmark                          2
Mozambique                       2
Afghanistan                      2
Ivory Coast                      2
Macau                            2
Burundi                          2
China                            2
Ireland                          2
Angola                           2
Libya                            2
Myanmar                          1
Equatorial Guinea                1
Morocco                          1
Peru                             1
Central African Republic         1
Israel                           1
Guatemala                        1
Iraq                             1
Finland                          1
Australia                        1
Norway                           1
United Arab Emirates             1
Barbados                         1
Sri Lanka                        1
Togo                             1
Thailand                         1
Ecuador                          1
Grenada                          1
Costa Rica                       1
Yemen                            1
Guyana                           1
Burkina Faso                     1
Liberia                          1
Egypt                            1
Spain                            1
Somalia                          1
Nepal                            1
India                            1
Name: count, dtype: int64

In [16]:
# Check for "not specified" under the country column
not_specified_country = df[df["country"] == "Not specified"]
print(f"Total 'Not specified' country rows: {len(not_specified_country)}")
print(not_specified_country["location"].value_counts())

Total 'Not specified' country rows: 61
location
Location: Regional / Global                            14
Medical                                                12
Location: Remote, Regional / Global                    11
Non-Medical                                             9
Remote                                                  8
Multiple Locations Considered                           4
Field Based                                             1
Location: Africa, Regional / Global                     1
Location: Remote Africa (Remote), Regional / Global     1
Name: count, dtype: int64

In [17]:
# Check items in not specified
exact_regional_global = df[df["location"] == "Location: Regional / Global"]
exact_regional_global[["organization", "location", "country", "work_arrangement"]]

,organization,location,country,work_arrangement
60,Reporters Sans Frontières (RSF),Location: Regional / Global,Not specified,Not specified
84,International Planned Parenthood Federation (IPPF),Location: Regional / Global,Not specified,Not specified
132,IPPF,Location: Regional / Global,Not specified,Not specified
140,Medair,Location: Regional / Global,Not specified,Not specified
170,African Tax Administration Forum (ATAF),Location: Regional / Global,Not specified,Not specified
181,Qcin,Location: Regional / Global,Not specified,Not specified
221,Mati Carbon,Location: Regional / Global,Not specified,Not specified
231,Global Citizen,Location: Regional / Global,Not specified,Not specified
260,Winrock International,Location: Regional / Global,Not specified,Not specified
463,CIMMYT - International Maize and Wheat Improvement Center,Location: Regional / Global,Not specified,Not specified
466,Deutsche Welle,Location: Regional / Global,Not specified,Not specified
494,One Acre Fund,Location: Regional / Global,Not specified,Not specified
498,Urgent Action Fund-Africa (UAF-Africa),Location: Regional / Global,Not specified,Not specified
519,Cultural Survival,Location: Regional / Global,Not specified,Not specified

In [18]:
exact_medical = df[df["location"] == "Medical"]
exact_medical[["organization", "location", "country", "work_arrangement"]]

   organization location        country work_arrangement
37      MSF USA  Medical  Not specified    Not specified
39      MSF USA  Medical  Not specified    Not specified
43      MSF USA  Medical  Not specified    Not specified
44      MSF USA  Medical  Not specified    Not specified
46      MSF USA  Medical  Not specified    Not specified
47      MSF USA  Medical  Not specified    Not specified
48      MSF USA  Medical  Not specified    Not specified
49      MSF USA  Medical  Not specified    Not specified
50      MSF USA  Medical  Not specified    Not specified
52      MSF USA  Medical  Not specified    Not specified
53      MSF USA  Medical  Not specified    Not specified
55      MSF USA  Medical  Not specified    Not specified

In [19]:
df["title"].value_counts()

title
Project Manager                                                                  3
Project Coordinator                                                              3
Grants Officer                                                                   2
Director                                                                         2
Executive Assistant                                                              2
Program Manager                                                                  2
Steel Cooperation Lead                                                           2
Partnership Finance Officer                                                      2
Associate Researcher, Global Programs                                            2
Finance Manager                                                                  2
Development & Outreach Department Intern                                         2
Chief Operating Officer                                                          2
Associate, Asia                                                                  2
Canada-Asia Young Professionals Fellowship Program                               2
Program Associate                                                                2
Development Associate                                                            2
Country Technical Lead                                                           2
Direct Marketing Executive                                                       2
Senior Lecturer - Counselling Psychology                                         2
Monitoring & Due Diligence Senior Coordinator                                    2
Media and Communications Lead                                                    2
Communications Associate                                                         2
Associate Director                                                               2
Senior Program Manager                                                           2
Technical Platform Manager                                                       1
Senior Growth & Partnerships Consultant                                          1
MEL Associate, Program Analytics and Learning Unit                               1
Account Director - Communications Research                                       1
Project Management Consultant                                                    1
Associate, Global Relationships & Resources                                      1
Senior Development Associate                                                     1
Senior/Executive, Administration                                                 1
Request for Proposals - Advancing Legal and Institutional Reform for the E...    1
Enterprise Account Manager                                                       1
Research Study on Female Genital Mutilation in Southern Africa - Consultant      1
Chief of Party, Food for Peace (FFP)                                             1
Psicologa E Operatrice Di Accoglienza Spazio Donna Napoli                        1
Inventory & AP Junior Accountant                                                 1
Monitoring, Evaluation, and Learning Lead                                        1
Deputy Country Representative for OPT, Based in Amman - Link for Internal ...    1
Accueillant E Bruxelles                                                          1
Consultant in Green Economy                                                      1
Fractional IT Manager                                                            1
Monitoring & Evaluation Associate - Global Fund TB Project                       1
Tupande AI Engineering Lead (Fixed-Term)                                         1
Contrôleur·euse De Gestion Junior (80-100%)                                      1
Analyst - Digital Transformation                                                 1
Head of Finance - AI Italy                                                       1
Post-Doctoral Fellow, Sorghum Breeding                                           1
Recruiter (Locally Recruited)                                                    1
Talent Acquisition and Engagement Officer                                        1
Manager, Events Communications and Audience Strategy                             1
Sales Associate                                                                  1
Area Manager                                                                     1
Safeguarding Officer                                                             1
Senior Advisor - Public Health                                                   1
Deputy Director for Programs (Non-Filipino)                                      1
Nigeria Human Resources Specialist                                               1
Senior Associate Director, Prospect Management                                   1
Tupande Automation Engineering Lead (Fixed-Term)                                 1
Youth Networker Acro                                                             1
Multi-Country Representative for Mena, Based in Amman - Link for Internal ...    1
Director, Sales Operations                                                       1
Chief Ethics, Risk & Compliance Officer                                          1
Impact Measurement and Management - Internship                                   1
Senior Programme Officer                                                         1
Operations Manager                                                               1
Senior Assessment Officer - PHU for OPT, Based in Amman - Link for Externa...    1
Digital Content Manager (Mat Cover)                                              1
Accueillant E Medibus Charleroi Et Ou La Louviere F H X                          1
Financial Literacy Specialist - 2025781                                          1
[Pipeline Position] Associate Research Scientist I (Statistics Department)...    1
HR Operations Specialist                                                         1
Manager, Fundraising                                                             1
Philanthropy Advisor                                                             1
Referentieverpleegkundige in De Diabeteszorg Antwerpen                           1
Senior Program Manager, GRIT Project                                             1
Junior Management Controller                                                     1
Associate Director, GeoTech Center                                               1
Investment Associate                                                             1
Senior Financing Partnerships Assistant                                          1
Monitoring and Evaluation Officer                                                1
Research Coordinator, Wyss Academy for Nature, Hub Southeast Asia, Recoftc...    1
Country Director, Recoftc Indonesia                                              1
Contrôleur De Gestion Junior                                                     1
Vice President, Atlantic Council and Senior Director, Scowcroft Center for...    1
Scientist - Regional Climate Modelling                                           1
Senior Program Associate                                                         1
Especialista Social De La Unidad De Implementación Del Proyecto                  1
Local Project Coordinator (f/m/d)                                                1
Recrutement D'un Consultant Chargé De L'évaluation Des Options De Particip...    1
Administrative Support UBEC PIU                                                  1
Consultoria Individual Especializada Em Sistematização De Diretrizes Técni...    1
Procurement Specialist                                                           1
Coordinador/A Nacional Y Especialista Social Del Proyecto Enable                 1
Head of Systems and Operations for DR Congo                                      1
Business & Projet Development Manager                                            1
Officer I, WASH                                                                  1
End-Line Evaluation Consultant                                                   1
Professionalisation Programme Officer                                            1
GEDSI Specialist (Consultant)                                                    1
Systems Support Analyst (CRM & Ticketing)                                        1
Senior Internal Auditor                                                          1
VAC-61908 Civil Engineer                                                         1
Associate Retirement Benefits Officer                                            1
Investment Manager                                                               1
Mobile Data Assistant                                                            1
Medisch Secretariaat Antwerpen                                                   1
Finance Data Analyst - 120                                                       1
Chief of Staff to the CEO                                                        1
Executive Coordinator                                                            1
Senior Consultant in Evaluation                                                  1
Administrative Officer                                                           1
Formatrice/Tore E Focal Point Scuole                                             1
Behavioral Health Services Manager                                               1
Operations & Legal Administrator (US)                                            1
Medical Practice Assistant                                                       1
Associate General Counsel                                                        1
Integrated Fundraising Coordinator                                               1
Financial Controller                                                             1
Visiting Professorship in the Political Economy of the Middle East (Open R...    1
Cluster Director                                                                 1
Team Leader - Bridge Project                                                     1
Finance Business Partner, Cross-Cutting Programmes                               1
Team Leader, Venezuela Scoping Mission                                           1
Partnership Coordinator                                                          1
Program Manager, Global Energy Transition Initiative                             1
RDP Technical Specialist                                                         1
E T Consultant – Program Coordinator                                             1
Head of Field Office                                                             1
Administrative and Financial Assistant, GEF Project in Equatorial Guinea         1
Sectoral Technical Experts                                                       1
Supply Chain Manager                                                             1
Supply Chain Assistant                                                           1
Long-Term Agreement of Individual Consultant as Graphic Designer for Human...    1
Senior Fellow and Director, the Technology and Global Security Program           1
Grant Accounting Manager                                                         1
SRH Manager                                                                      1
Fertilizer Procurement Associate                                                 1
Creative Lead                                                                    1
National Consultants and Field Coordinators (Roster)                             1
Senior Executive, Executive Office                                               1
Sales Officer                                                                    1
GWEP Technical Advisor                                                           1
Malawi Market Access Lead                                                        1
Senior Project Coordinator                                                       1
Senior Analyst, Middle East                                                      1
Facility Operations Manager                                                      1
Country Representative Tanzania                                                  1
Mid-senior Researcher in Data Systems and Digital Governance                     1
Senior Associate                                                                 1
Supporting Business Formalization and Delivery of Financial Education and ...    1
Country Director Cambodia                                                        1
Accounts Receivable Specialist                                                   1
Data & Technology Manager                                                        1
Counseling Team Manager - 2025747                                                1
Iter Postgraduate Opportunities - All Disciplines                                1
Malawi Agricultural Innovations Lead                                             1
Networks Administrator                                                           1
Digital Systems Capacity Building Consultant                                     1
Community Care & Integration Specialist - Limited Term - 2025779                 1
Senior Director, Critical Minerals and Community Positive Energy Transition      1
Project Administrator                                                            1
Ppca Secretariat Coordinator                                                     1
Partnership Excellence Specialist (Internationally Recruited)                    1
Program Officer                                                                  1
Feminist Knowledge Leadership Assistant                                          1
Rwanda Scale Innovations Intern                                                  1
Senior Livelihoods and Economic Inclusion Officer                                1
Risk Operations Officer                                                          1
Programme Policy Officer (Emergency Preparedness Response) NOB                   1
Fall 2026 & Spring 2027 Academic Year Externship                                 1
Investor Relations Graduate Trainee                                              1
Global MEL Senior Associate (Fixed-Term)                                         1
Internship - Research & Innovation Policies                                      1
Tupande Controls, Health & Safety Specialist                                     1
Tupande Market Access Strategy and Operations Associate                          1
Communications Internship Fall 2026                                              1
Fall 2026 - Research Internship for the Director of Programs - Fully Remot...    1
Rwanda Plant Nutrient Management Research & Lab Senior Specialist (Renewab...    1
Zambia People Lead                                                               1
Head of Systems and Operations                                                   1
Business Support Officer                                                         1
Sustainable Agriculture Innovation Lead                                          1
Rwanda Recrutement Stagiaire                                                     1
Global Program Owner                                                             1
Senior Product Manager                                                           1
Officer, Logistics & Project Management                                          1
Head of Logistics & infrastructure                                               1
Proxy Product Owner - ERP Project                                                1
Assistant.E Controle De Gestion Siege (H/F)                                      1
Assistant.E Archiviste (H/F)                                                     1
Senior IPC Manager - Ituri                                                       1
RLO Fund Officer                                                                 1
Digital Product Specialist                                                       1
Project Coordinator RDC                                                          1
Regional Legal Counsel, Africa (Locally Recruited)                               1
Philanthropy Coordinator                                                         1
Senior Manager, Learning & Development                                           1
Head of Program Finance (Internationally Recruited)                              1
Senior Mentor – Illicit Gold Networks and Supply Chain                           1
Medical Department Support Officer                                               1
Project Officer                                                                  1
Sustainability Procurement Advisor                                               1
Enterprise Systems Analyst, Finance                                              1
Creative Producer                                                                1
Senior Manager, Principal Communications & Strategic Engagements                 1
Senior Development Manager                                                       1
Business Systems Analyst, Payroll Systems                                        1
Operations Manager Atlas Logistique                                              1
Research Associate (PSA) - Inequality Between and Within Countries               1
Training & Educational Analyst (PSA Contract                                     1
Field Officer                                                                    1
Media Officer                                                                    1
Chief Strategy Officer                                                           1
Field Accountant                                                                 1
Safety & Security Manager                                                        1
Senior Administrative Assistant- Legal & Human Resources                         1
Executive Director, Marketing and Communications                                 1
Senior Coordinator, Annual Giving                                                1
Program Grants Officer (Latin America)                                           1
Autonomous Vehicles Lead                                                         1
Senior Engineering Manager, Platform Engineering & Data Systems                  1
Project Officer, Livelihoods Mount Elgon Project                                 1
ITSM Change Management Analyst                                                   1
Laboratory Technologist                                                          1
Administrative Assistant                                                         1
OCDI Program and Grants Associate                                                1
Monitoring, Evaluation, Accountability and Learning Manager, Africa              1
Mid–senior Researcher                                                            1
Community Development Coordinator                                                1
Climate Finance Officer                                                          1
Government Affairs & Advocacy Lead                                               1
IT Officer – Global Support                                                      1
Formatrice/Tore E Facilitatrice/Tore                                             1
Human Resources Specialist                                                       1
Program Manager - Surge and Sustain                                              1
Principal Counterterrorism and Transnational Criminal Organization Expert ...    1
Information Security Operations Officer                                          1
Partnership and Grants Manager                                                   1

In [20]:
df["job_category"].value_counts()

job_category
Other/Uncategorized           137
Program/Project Management     70
Operations/Admin               51
Finance                        37
IT/Tech                        34
Non-English/Unclassified       32
Health                         28
Communications                 28
Research                       25
Fundraising/Grants             19
M&E                            18
HR                             15
Logistics                      15
Legal                          13
Advocacy/Policy                 8
Name: count, dtype: int64

In [21]:
# Non_medical category which was labelled as "not specified" in the country column
# This suggests despite the non-medical column not providing any information to the country column, it does provide info
# to the title and job_category column
non_medical_check = df[(df["organization"] == "MSF USA") & (df["location"] == "Non-Medical")]
print(non_medical_check[["title", "job_category"]].to_string())

                             title                job_category
38          Communications Manager              Communications
40                Health Promoters                      Health
41       HR/Finance Administrators                     Finance
42    Humanitarian Affairs Officer            Operations/Admin
45                  Legal Advisors                       Legal
51            Project Coordinators  Program/Project Management
54             Supply Logisticians                   Logistics
56          Technical Logisticians                   Logistics
57  Water & Sanitation Specialists         Other/Uncategorized

In [22]:
# Same noticable thing, the regional/global catgory under the country column is categorised as "not specified"
# but still holds data of other columns ie title and job_category columns respectively
regional_global_check = df[df["location"] == "Location: Regional / Global"]
print(regional_global_check[["organization", "title", "job_category"]].to_string())

                                                  organization                                                                          title                job_category
60                             Reporters Sans Frontières (RSF)  Econometric Foresight Study on the Impact of Content Prominence Requiremen...              Communications
84          International Planned Parenthood Federation (IPPF)                                 Data Systems & MA Support Officer (Consultant)                     IT/Tech
132                                                       IPPF  Consultancy: Strategic Support for Advocacy Innovation & Organizational Le...             Advocacy/Policy
140                                                     Medair                                                Health Project Manager, Generic                      Health
170                    African Tax Administration Forum (ATAF)                                                               ATAF Internships         Other/Uncategorized
181                                                       Qcin                      Coordinator Consultant (Policy & Investment Facilitation)             Advocacy/Policy
221                                                Mati Carbon                                                                      Executive         Other/Uncategorized
231                                             Global Citizen                                            Director, PR & Communications, EMEA              Communications
260                                      Winrock International                     Registry Officer/Registry Manager, Depending on Experience            Operations/Admin
463  CIMMYT - International Maize and Wheat Improvement Center                             Regional Legal Counsel, Africa (Locally Recruited)                       Legal
466                                             Deutsche Welle                                                          Project Administrator  Program/Project Management
494                                              One Acre Fund                                                                  Creative Lead         Other/Uncategorized
498                     Urgent Action Fund-Africa (UAF-Africa)                                        Feminist Knowledge Leadership Assistant         Other/Uncategorized
519                                          Cultural Survival  Fall 2026 - Research Internship for the Director of Programs - Fully Remot...                    Research

In [23]:
# Check for remote africa in the "not specified" category under the country column

remote_africa_check = df[df["location"].str.contains("Remote Africa", case=False, na=False)]
print(remote_africa_check[["organization", "title", "job_category"]].to_string())

    organization                          title                job_category
336        YLabs  Project Management Consultant  Program/Project Management

In [27]:
df = pd.read_csv("data/master_dataset_cleaned.csv")
df.columns.tolist()

['organization',
 'title',
 'location',
 'date_posted',
 'deadline',
 'source_url',
 'country',
 'work_arrangement',
 'country_region']

In [28]:
# Check for missing countries
other_countries = df[df["country_region"] == "Other"]["country"].value_counts()
print(other_countries)

country
Palestinian Territory    7
Turkey                   5
Madagascar               4
Syrian Arab Republic     3
Afghanistan              2
Albania                  2
New Caledonia            2
Costa Rica               2
Hungary                  2
Bulgaria                 2
Grenada                  2
Macau                    2
Barbados                 1
Netherlands Antilles     1
Equatorial Guinea        1
Guatemala                1
Uzbekistan               1
Palau                    1
Guyana                   1
Cape Verde               1
Name: count, dtype: int64

In [ ]:
# Check existing country - regions in the dataframe
df = pd.read_csv("data/master_dataset_cleaned.csv")
print(sorted(df["country_region"].unique()))

['Asia', 'Central Africa', 'East Africa', 'Europe', 'Middle East', 'North Africa', 'North America', 'Not specified', 'Oceania', 'Other', 'South America', 'Southern Africa', 'West Africa']

In [33]:
df_check = pd.read_csv("data/master_dataset_v3.csv")
print(df_check[df_check["title"].isna()])

    organization title location date_posted deadline  \
681          NaN   NaN      NaN         NaN      NaN
682          NaN   NaN      NaN         NaN      NaN
683          NaN   NaN      NaN         NaN      NaN
684          NaN   NaN      NaN         NaN      NaN
685          NaN   NaN      NaN         NaN      NaN
686          NaN   NaN      NaN         NaN      NaN
687          NaN   NaN      NaN         NaN      NaN
688          NaN   NaN      NaN         NaN      NaN

                                                   source_url        country  \
681  https://devnetjobs.org/jobdescription.aspx?job_id=310683  Not specified
682               https://devnetjobs.org/valuemembership.aspx  Not specified
683  https://devnetjobs.org/jobdescription.aspx?job_id=310759  Not specified
684  https://devnetjobs.org/jobdescription.aspx?job_id=310757  Not specified
685  https://devnetjobs.org/jobdescription.aspx?job_id=311180  Not specified
686               https://devnetjobs.org/valuemembership.aspx  Not specified
687  https://devnetjobs.org/jobdescription.aspx?job_id=310862  Not specified
688  https://devnetjobs.org/jobdescription.aspx?job_id=310864  Not specified

    work_arrangement country_region
681    Not specified  Not specified
682    Not specified  Not specified
683    Not specified  Not specified
684    Not specified  Not specified
685    Not specified  Not specified
686    Not specified  Not specified
687    Not specified  Not specified
688    Not specified  Not specified

In [39]:
df.head()

,organization,title,location,date_posted,deadline,source_url,country,work_arrangement,country_region
0,Amref,Monitoring & Evaluation Associate - Global Fund TB Project,Nairobi,2026-07-14T12:36:37.738Z,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137657149,Kenya,Onsite,East Africa
1,Amref,Program Manager-SRHR,Kampala,2026-07-14T07:50:55.688Z,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000137606414,Uganda,Onsite,East Africa
2,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07T08:50:22.263Z,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136172959,Kenya,Onsite,East Africa
3,Amref,Senior Lecturer - Clinical psychology,Nairobi,2026-07-07T08:48:46.626Z,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136171985,Kenya,Onsite,East Africa
4,Amref,Senior Lecturer - Counselling Psychology,Nairobi,2026-07-07T08:33:51.023Z,NaN,https://api.smartrecruiters.com/v1/companies/AmrefHealthAfrica4/postings/744000136169179,Kenya,Onsite,East Africa

In [40]:
df["work_arrangement"].value_counts()

work_arrangement
Onsite             576
Regional/Global     38
Remote              34
Not specified       34
Hybrid               7
Name: count, dtype: int64

In [ ]:
# Load data
import pandas as pd
df = pd.read_csv("data/master_dataset_cleaned.csv")

# Filter rows where work_arrangement is Regional/Global
regional_global = df[df['work_arrangement'] == 'Regional/Global']

# Check how many
print(f"Found {len(regional_global)} rows with 'Regional/Global'")

Found 38 rows with 'Regional/Global'

In [45]:
# See the actual location text for these rows
print(regional_global[['location', 'country', 'work_arrangement']].head(20))

                                                             location  \
63                                        Location: Regional / Global
98                                        Location: Regional / Global
103                               Location: Remote, Regional / Global
154                               Location: Remote, Regional / Global
165                                       Location: Regional / Global
176                                       Location: Regional / Global
184                                       Location: Regional / Global
204  Location: Delhi or Manila, Regional / Global, Philippines, India
205                                       Location: Regional / Global
218                                       Location: Regional / Global
232                                       Location: Regional / Global
266                               Location: Remote, Regional / Global
278                               Location: Africa, Regional / Global
285                                       Location: Regional / Global
290                               Location: Remote, Regional / Global
297                                       Location: Regional / Global
322                                       Location: Regional / Global
338                                       Location: Regional / Global
379                               Location: Remote, Regional / Global
386                               Location: Remote, Regional / Global

           country work_arrangement
63   Not specified  Regional/Global
98   Not specified  Regional/Global
103  Not specified  Regional/Global
154  Not specified  Regional/Global
165  Not specified  Regional/Global
176  Not specified  Regional/Global
184  Not specified  Regional/Global
204          India  Regional/Global
205  Not specified  Regional/Global
218  Not specified  Regional/Global
232  Not specified  Regional/Global
266  Not specified  Regional/Global
278  Not specified  Regional/Global
285  Not specified  Regional/Global
290  Not specified  Regional/Global
297  Not specified  Regional/Global
322  Not specified  Regional/Global
338  Not specified  Regional/Global
379  Not specified  Regional/Global
386  Not specified  Regional/Global

In [46]:
# See what patterns exist
print(regional_global['location'].value_counts())

location
Location: Regional / Global                                                                                    18
Location: Remote, Regional / Global                                                                            13
Location: Delhi or Manila, Regional / Global, Philippines, India                                                1
Location: Africa, Regional / Global                                                                             1
Location: Manila, Nairobi, Lusaka, Rabat, or Senegal, Regional / Global                                         1
Location: Remote Africa (Remote), Regional / Global                                                             1
Location: Indonesia, Philippines ,Thailand ,Vietnam, Regional / Global                                          1
Location: Regional, Americas and the Caribbean, With a Preference for Mexico or Trinidad and Tobago, Mexico     1
Location: Global Hybrid, United Kingdom                                                                         1
Name: count, dtype: int64

In [47]:
# See if there are any other interesting patterns
print("\nUnique location values for Regional/Global:")
for loc in regional_global['location'].unique():
    print(f"  {loc}")

Unique location values for Regional/Global:
  Location: Regional / Global
  Location: Remote, Regional / Global
  Location: Delhi or Manila, Regional / Global, Philippines, India
  Location: Africa, Regional / Global
  Location: Manila, Nairobi, Lusaka, Rabat, or Senegal, Regional / Global
  Location: Remote Africa (Remote), Regional / Global
  Location: Indonesia, Philippines ,Thailand ,Vietnam, Regional / Global
  Location: Regional, Americas and the Caribbean, With a Preference for Mexico or Trinidad and Tobago, Mexico
  Location: Global Hybrid, United Kingdom

In [48]:
# See what countries these rows have
print("\nCountry distribution for Regional/Global rows:")
print(regional_global['country'].value_counts())

Country distribution for Regional/Global rows:
country
Not specified     33
India              1
Senegal            1
Vietnam            1
Mexico             1
United Kingdom     1
Name: count, dtype: int64